name: Windows 64-bit

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Build GUI
      run: dotnet publish HEI.GUI/HEI.GUI.csproj -c Release -v q --self-contained -r win-x64
    - name: Build CLI
      run: dotnet publish HEI.CLI/HEI.CLI.csproj -c Release -v q --self-contained -r win-x64
    - name: Build Web
      run: dotnet publish HEI.Web/HEI.Web.csproj -c Release -v q --self-contained -r win-x64
    - name: Run Unit Tests
      run: dotnet test HEI.Core.Tests/HEI.Core.Tests.csproj -c Release -v q
    - name: Run CLI Tests
      run: dotnet test HEI.CLI.Tests/HEI.CLI.Tests.csproj -c Release -v q
    - name: Run GUI Tests
      run: dotnet test HEI.GUI.Tests/HEI.GUI.Tests.csproj -c Release -v q
    - name: Run GUI Headless Tests
      run: dotnet test HEI.GUI.HeadlessTests/HEI.GUI.HeadlessTests.csproj -c Release -v q
    - name: Run Web Tests
      run: dotnet test HEI.Web.Tests/HEI.Web.Tests.csproj -c Release -v q
    - name: Install FFmpeg
      run: choco install ffmpeg -y --no-progress
    - name: Run Integration Tests
      run: dotnet test HEI.IntegrationTests/HEI.IntegrationTests.csproj -c Release -v normal
